############################################################
@local = https://localhost:6969
@deployed = https://

############################################################
POST {{deployed}}/...
content-type: application/json

{
    "a": "a"
}

############################################################
POST {{local}}/login
content-type: application/json

{
    "secret": "defaultsecret"
}

###
POST {{local}}/login
content-type: application/json

{
    "secret": "wrongsecret"
}

###
POST {{local}}/tokenCheck
content-type: application/json

{
    "token": "iKGpmkRdqc5wrYfhoBJ8"
}

###
POST {{local}}/update
content-type: application/json

{
    "token": "iKGpmkRdqc5wrYfhoBJ8"
}

###
POST {{local}}/discard
content-type: application/json

{
    "token": "iKGpmkRdqc5wrYfhoBJ8"
}

###
POST {{local}}/apply
content-type: application/json

{
    "token": "iKGpmkRdqc5wrYfhoBJ8"
}k